name: Pipe

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run test Android
        if: always()
        env:
          BS_DEVICE: Google Pixel 3
          BS_VERSION: '9.0'
          BS_USER: ${{ secrets.BS_USER }}
          BS_KEY: ${{ secrets.BS_KEY }}
          BS_HASH: ${{ secrets.BS_HASH }}
        run: mvn clean test

      - name: Generate verify cucumber report
        run: mvn verify -DskipTests

      - name: Move report to folder reports
        run: mvn test -Dtest=ReportHelper

      - name: Build and deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./target/cucumber-html-reports/embeddings/*.html
