name: Pipe

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run test Android
        if: always()
        env:
          BS_DEVICE: Google Pixel 3
          BS_VERSION: '9.0'
          BS_USER: ${{ secrets.BS_USER }}
          BS_KEY: ${{ secrets.BS_KEY }}
          BS_HASH: ${{ secrets.BS_HASH }}
        run: mvn clean test

      - name: Generate verify cucumber report
        run: mvn verify -DskipTests

      - name: Deploy to GitHub Pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./target/cucumber-report-html/feature-overview.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
